sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
       - docker build -t rawdataservice .
       - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
       - docker images
       - docker tag rawdataservice $DOCKER_USERNAME/rawdataservice
       - docker push $DOCKER_USERNAME/rawdataservice
#    - stage: test
#      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
#    - script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
